btn1 = button(main_screen, "Add Book", to_add_book_screen)
btn2 = button(main_screen, "View Books", to_view_books_screen)
btn3 = button(main_screen, "Search Book", to_search_book_screen)
btn4 = button(add_book_screen , "Back to action selection", to_main_screen)
btn5 = button(search_book_screen , "Back to action selection", to_main_screen)
btn6 = button(view_books_screen , "Back to action selection", to_main_screen)